plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/michaelperinwogenburg/Desktop/big-challenge/1-in-a-billion-v2/website"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]